name: Environments

on:
  push:
    branches: [main]
env:
  dev_token_var: ${{vars.DEV_TOKEN}}
  dev_token_secret: ${{secrets.DEV_TOKEN}}

jobs:
  build:
    runs-on: macos-latest

    steps:
      #   - name: Checkout code
      #     uses: actions/checkout@v2
      #   - name: Setup Flutter
      #     uses: subosito/flutter-action@v2
      #     with:
      #       channel: "stable"
      #   - name: Called Dependencies
      #     run: flutter pub get
      - name: print variables
        run: echo "vars:${{vars.DEV_TOKEN}} secrets:${{secrets.DEV_TOKEN}}"
