name: Environments

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    env:
      dev_token_var: ${{vars.TOKEN}}
      dev_token_secret: ${{secrets.TOKEN}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Called Dependencies
        run: flutter pub get
      - name: print variables
        run: echo "public:$dev_token_var secrets:$dev_token_secret"
  flutter-masters-production:
    runs-on: ubuntu-latest

    environment: production

    env:
      vars_token_production: ${{vars.TOKEN}}
      secrets_token_production: ${{secrets.TOKEN}}

    steps:
      - name: print variables
        run: echo "public:$vars_token_production secrets:$secrets_token_production"
