name: Environments

on:
  push:
    branches: [main]

env:
  token: ${{vars.ENV_TOKEN}}
  secret_token: ${{secrets.TOKEN}}

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Called Dependencies
        run: flutter pub get
      - name: Print Vars and Secrets
        run: echo "token:${{env.token}} secret:${{env.secret_token}}"

  flutter-masters-production:
    runs-on: ubuntu-latest
    environment: production
    env:
      token_prod: ${{vars.TOKEN}}
      secret_token_prod: ${{secrets.TOKEN}}

    steps:
      - name: RUN ECHO
        run: echo "secret:${{env.secret_token_prod}} public:${{env.token_prod}}"
