name: GA-COMBINE-FLUTTER
permissions: write-all

on:
  push:
    branches: [main]

jobs:
  flutter-masters-build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "11"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Called Dependencies
        run: flutter pub get

      - name: ios pod repo update
        run: pod repo update
        working-directory: ios

      - name: build ios
        run: flutter build ios --release --no-codesign

      - run: mkdir Payload
        working-directory: build/ios/iphoneos

      - run: mv Runner.app/ Payload
        working-directory: build/ios/iphoneos

      - name: Zip output
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      - name: ios-ipa
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true

  flutter-masters-build-apk-on-ubuntu:
    runs-on: ubuntu-latest
    needs: [flutter-masters-build-ios]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "11"
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Called Dependencies
        run: flutter pub get
      - name: build apk
        run: flutter build apk --debug
      - name: build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/apk/debug/app-debug.apk
          tag: v1.0
          overwrite: true
