name: GA-COMBINE-FLUTTER

on:
  push:
    branches: [main]

jobs:
  flutter-masters-build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "11"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Called Dependencies
        run: flutter pub get

      - name: build ios
        run: flutter build ios --release --no-codesign
      - name: Create IPA
        run: xcodebuild -exportArchive -archivePath build/ios/iphoneos/Runner.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath build/ios/ipa
      - name: build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: build/ios/ipa
#   flutter-masters-build-apk-on-ubuntu:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - uses: actions/setup-java@v4
#         with:
#           distribution: "zulu"
#           java-version: "11"

#       - name: Setup Flutter
#         uses: subosito/flutter-action@v2
#         with:
#           channel: "stable"
#       - name: Called Dependencies
#         run: flutter pub get

#       - name: build apk
#         run: flutter build apk --debug

#       - name: build artifacts
#         uses: actions/upload-artifact@v4
#         with:
#           name: My Android APK
#           path: build/app/outputs/apk/debug/app-debug.apk
