name: GA-COMBINE-FLUTTER
permissions: write-all

on:
  push:
    branches: [main]

jobs:
  flutter-masters-build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "11"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64

      - name: Called Dependencies
        run: flutter pub get

      - name: ios pod repo update
        run: pod repo update
        working-directory: ios

      - name: build ipa file
        run: flutter build ipa --no-codesign

      - name: generate ipa by flutter
        run: flutter build ipa  --export-options-plist="build/ios/archive/Runner.xcarchive/Info.plist"
      - name: build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/ios/ipa/books.ipa
          tag: v1.0
          overwrite: true
#   flutter-masters-build-apk-on-ubuntu:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#       - uses: actions/setup-java@v4
#         with:
#           distribution: "zulu"
#           java-version: "11"
#       - name: Setup Flutter
#         uses: subosito/flutter-action@v2
#         with:
#           channel: "stable"
#       - name: Called Dependencies
#         run: flutter pub get
#       - name: build apk
#         run: flutter build apk --release
#       - name: build artifacts
#         uses: actions/upload-artifact@v4
#         with:
#           name: android-apk
#           path: build/app/outputs/apk/release/app-release.apk
#           tag: v1.0
#           overwrite: true
